=== issguoqi/CodeGenerator/src/main/java/com/nxllxn/codegenerator/config/xml/confguration-1.0.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT context (properties?,property*,projectBaseInfo,mavenCoordinate,jdbcConnection,
                javaTypeResolver?,javaModelGenerator?,keyDefinitionGenerator?,
                javaClientGenerator?,sqlMapGenerator?,
                serviceGenerator?,serviceImplGenerator?,controllerGenerator?,
                exceptionHandlerGenerator,applicationGenerator?,configGenerator?,pomGenerator?,
                commentGenerator?,plugin*,table*)>

        <!ELEMENT properties EMPTY>
        <!ATTLIST properties
                resource CDATA #IMPLIED
                url CDATA #IMPLIED>

        <!ELEMENT projectBaseInfo EMPTY>
        <!ATTLIST projectBaseInfo
                projectName CDATA #REQUIRED
                sourceDirectory CDATA #REQUIRED
                resourcesDirectory CDATA #REQUIRED
                rootPackage CDATA #REQUIRED>

        <!ELEMENT mavenCoordinate EMPTY>
        <!ATTLIST mavenCoordinate
                groupId CDATA #REQUIRED
                artifactId CDATA #REQUIRED
                version CDATA #REQUIRED>


        <!ELEMENT property EMPTY>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED>

        <!ELEMENT jdbcConnection (property*)>
        <!ATTLIST jdbcConnection
                driverClassName CDATA #REQUIRED
                connectionURL CDATA #REQUIRED
                userName CDATA #REQUIRED
                password CDATA #REQUIRED>

        <!ELEMENT javaTypeResolver EMPTY>
        <!ATTLIST javaTypeResolver
                type CDATA #REQUIRED>

        <!ELEMENT javaModelGenerator EMPTY>
        <!ATTLIST javaModelGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED>

        <!ELEMENT sqlMapGenerator EMPTY>
        <!ATTLIST sqlMapGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED
                publicId CDATA #REQUIRED
                systemId CDATA #REQUIRED
                nameSpacePackage CDATA #REQUIRED>

        <!ELEMENT javaClientGenerator EMPTY>
        <!ATTLIST javaClientGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED>

        <!ELEMENT keyDefinitionGenerator EMPTY>
        <!ATTLIST keyDefinitionGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED>

        <!ELEMENT serviceGenerator EMPTY>
        <!ATTLIST serviceGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED>

        <!ELEMENT serviceImplGenerator EMPTY>
        <!ATTLIST serviceImplGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED>

        <!ELEMENT controllerGenerator EMPTY>
        <!ATTLIST controllerGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED>

        <!ELEMENT exceptionHandlerGenerator EMPTY>
        <!ATTLIST exceptionHandlerGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED>

        <!ELEMENT applicationGenerator EMPTY>
        <!ATTLIST applicationGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED>

        <!ELEMENT configGenerator EMPTY>
        <!ATTLIST configGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED>

        <!ELEMENT pomGenerator EMPTY>
        <!ATTLIST pomGenerator
                type CDATA #REQUIRED
                targetPackage CDATA #REQUIRED
                targetDirectory CDATA #REQUIRED
                publicId CDATA #REQUIRED
                systemId CDATA #REQUIRED
                namespace CDATA #REQUIRED
                xsiNamespace CDATA #REQUIRED>

        <!ELEMENT plugin EMPTY>
        <!ATTLIST plugin
                type CDATA #REQUIRED>

        <!ELEMENT commentGenerator EMPTY>
        <!ATTLIST commentGenerator
                type CDATA #REQUIRED>

        <!ELEMENT table (property*,tableRenaming*,columnRenaming*,columnOverride*,columnIgnore*)>
        <!ATTLIST table
                tableName CDATA #REQUIRED
                entityName CDATA #REQUIRED>

        <!ELEMENT tableRenaming EMPTY>
        <!ATTLIST tableRenaming
                searchFor CDATA #REQUIRED
                replaceWith CDATA #REQUIRED>

        <!ELEMENT columnRenaming EMPTY>
        <!ATTLIST columnRenaming
                searchFor CDATA #REQUIRED
                replaceWith CDATA #REQUIRED>

        <!ELEMENT columnOverride (property*)>
        <!ATTLIST columnOverride
                column CDATA #REQUIRED>

        <!ELEMENT columnIgnore EMPTY>
        <!ATTLIST columnIgnore
                column CDATA #REQUIRED>

=== issguoqi/CodeGenerator/src/main/resources/Configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE context
        PUBLIC ""
        "com/nxl/codegenerator/config/xml/confguration-1.0.dtd">

<context>
    <properties resource="jdbc.properties"/>

    <property name="autoDelimitKeywords" value="false"/>
    <property name="javaFileEncoding" value="UTF-8"/>
    <property name="beginningDelimiter" value="`"/>
    <property name="endingDelimiter" value="`"/>

    <projectBaseInfo
            projectName="GeneratedProject"
            sourceDirectory="src/main/java"
            resourcesDirectory="src/main/resources"
            rootPackage="com.foo.kie"/>

    <mavenCoordinate
            groupId="com.foo"
            artifactId="kie"
            version="1.0.0-SNAPSHOT"/>

    <jdbcConnection
            driverClassName="${jdbc.driverClassName}"
            connectionURL="${jdbc.connectionURL}"
            userName="${jdbc.userName}"
            password="${jdbc.password}">
        <property name="allowMultipleQuery" value="true"/>
    </jdbcConnection>

    <javaTypeResolver
            type="com.nxllxn.codegenerator.jdbc.java.JavaTypeResolver"/>

    <javaModelGenerator
            type="com.nxllxn.codegenerator.codegen.generator.entity.EntityCodeGenerator"
            targetPackage="com.foo.kie.entities"
            targetDirectory="src/main/java"/>

    <keyDefinitionGenerator
            type="com.nxllxn.codegenerator.codegen.generator.key.KeyCodeGenerator"
            targetPackage="com.foo.kie.key"
            targetDirectory="src/main/java"/>

    <javaClientGenerator
            type="com.nxllxn.codegenerator.codegen.generator.mapper.MapperCodeGenerator"
            targetPackage="com.foo.kie.mapper"
            targetDirectory="src/main/java"/>

    <sqlMapGenerator
            type="com.nxllxn.codegenerator.codegen.generator.xml.XmlCodeGenerator"
            targetPackage="com.foo.kie.mapper.xml"
            targetDirectory="src/main/java"
            publicId="-//mybatis.org//DTD Mapper 3.0//EN"
            systemId="http://mybatis.org/dtd/mybatis-3-mapper.dtd"
            nameSpacePackage=""/>

    <serviceGenerator
            type="com.nxllxn.codegenerator.codegen.generator.service.ServiceCodeGenerator"
            targetPackage="com.foo.kie.service"
            targetDirectory="src/main/java"/>

    <serviceImplGenerator
            type="com.nxllxn.codegenerator.codegen.generator.serviceimpl.ServiceImplCodeGenerator"
            targetPackage="com.foo.kie.service.impl"
            targetDirectory="src/main/java"/>

    <controllerGenerator
            type="com.nxllxn.codegenerator.codegen.generator.controller.ControllerCodeGenerator"
            targetPackage="com.foo.kie.controller"
            targetDirectory="src/main/java"/>

    <exceptionHandlerGenerator
            type="com.nxllxn.codegenerator.codegen.generator.exception.ExceptionHandlerCodeGenerator"
            targetPackage="com.foo.kie.exception"
            targetDirectory="src/main/java"/>

    <applicationGenerator
            type="com.nxllxn.codegenerator.codegen.generator.application.ApplicationCodeGenerator"
            targetPackage="com.foo.kie"
            targetDirectory="src/main/java"/>

    <configGenerator
            type="com.nxllxn.codegenerator.codegen.generator.config.ConfigCodeGenerator"
            targetPackage=""
            targetDirectory="src/main/resources"/>

    <pomGenerator
            type="com.nxllxn.codegenerator.codegen.generator.maven.PomCodeGenerator"
            targetPackage=""
            targetDirectory=""
            publicId="-//mybatis.org//DTD Mapper 3.0//EN"
            systemId="http://mybatis.org/dtd/mybatis-3-mapper.dtd"
            namespace="http://maven.apache.org/POM/4.0.0"
            xsiNamespace="http://www.w3.org/2001/XMLSchema-instance"/>

    <!--TODO add later-->
    <!--<commentGenerator
            type=""/>

    <plugin
            type=""/>-->

    <!--TODO fix later,getTables方法应该按照配置的表名进行表信息获取，目前为获取全部表-->
    <table tableName="%" entityName="">
        <tableRenaming searchFor="prefix" replaceWith=""/><!--表重命名-->

        <columnRenaming searchFor="prefix" replaceWith=""/><!--列重命名-->

        <columnOverride column="idxxx"><!--列配置覆盖-->
            <property name="property" value="recordId"/>
            <property name="javaType" value="java.lang.Integer"/>
            <property name="jdbcType" value="integer"/>
            <property name="typeHandler" value=""/>
        </columnOverride>

        <columnIgnore column="detail"/><!--列忽略-->
    </table>
</context>
